### ISSUE TITLE
EXE file

### ISSUE THREAD

**Issue by kaznakov** [Dakara93/wx2pfpx#17]
Hello. Sorry for inconvinience, but I cant find an exe file in archive.

**Comment by aloys-c** [comment]
Hello,

It should definitely be there, are you downloading from the "releases" section ? My guess is your antivirus is deleting it as it's not signed and thus detected as a potential malware...

**Comment by kaznakov** [comment]
I dont have any Antivirus :( Here is the initial packge.
![photo_2024-04-17_15-56-06](https://github.com/aloys-c/wx2pfpx/assets/167316722/d18992fa-8c2b-4ed5-8aac-3bbf3ba86b6b)

**Comment by kaznakov** [comment]
But I have Wx2f.exe in 'src' folder.

**Comment by aloys-c** [comment]
On the main github page on the right there is a releases section in which you can download the latest archive…

**Comment by kaznakov** [comment]
That's how it was downloaded. All 3 packages are the same and no exe file in any.
![photo_2024-04-17_17-57-13](https://github.com/aloys-c/wx2pfpx/assets/167316722/6e6e23a9-e0ee-4a8d-a8df-c3cb6da3e471)

**Comment by aloys-c** [comment]
The only one you need is the first one :  [wx2pfpx-v2.6.3.zip](https://github.com/aloys-c/wx2pfpx/releases/download/v2.6.3/wx2pfpx-v2.6.3.zip)

I just downloaded it and the exe is indeed inside, don't know what more to tell you, it has been downloaded more than 150 times...

**Comment by kaznakov** [comment]
I can see it after downloading to my phone. Something is on my computer site. Will try from laptop. Thank you!

**Comment by braunsleger** [comment]
Click on the link he sent you here. You have downloaded the wrong file, just like me before. :)
