### ISSUE TITLE
Esto es un error del malwarebytes? Sus?

### ISSUE THREAD

**Issue by Narucriz** [Dakara93/wx2pfpx#19]
Malwarebytes
www.malwarebytes.com

-Detalles del registro-
Fecha del análisis: 23/9/2024
Hora del análisis: 0:03
Archivo de registro: 3bd2492a-7969-11ef-b69f-a036bc0c27fd.json

-Resumen del análisis-
Tipo de análisis: Análisis de amenazas
Análisis iniciado por:: Manual
Resultado: Completado
Objetos analizados: 257033
Amenazas detectadas: 2
Amenazas en cuarentena: 2
Tiempo transcurrido: 0 min, 46 seg

-Opciones de análisis-
Memoria: Activado
Inicio: Activado
Sistema de archivos: Activado
Archivo: Activado
Rootkits: Desactivado
Heurística: Activado
PUP: Detectar
PUM: Detectar

-Detalles del análisis-
Proceso: 0
(No hay elementos maliciosos detectados)

Módulo: 0
(No hay elementos maliciosos detectados)

Clave del registro: 0
(No hay elementos maliciosos detectados)

Valor del registro: 0
(No hay elementos maliciosos detectados)

Datos del registro: 0
(No hay elementos maliciosos detectados)

Secuencia de datos: 0
(No hay elementos maliciosos detectados)

Carpeta: 0
(No hay elementos maliciosos detectados)

Archivo: 2
Malware.AI.4227756526, C:\USERS\xxxx\DOWNLOADS\WX2PFPX-V2.6.3.ZIP, En cuarentena, 1000000, -67210770, 1.0.89579, D01B42590456D508FBFE71EE, dds, 03012664, 611A2B2D7455DB4F465925D020F2B575, 35EF4520A1243E9C4C21C3D0C95CB6749ADB57544116682674EFE53AFF6AF854
Malware.AI.4227756526, C:\USERS\xxxx\APPDATA\ROAMING\Microsoft\Windows\Recent\wx2pfpx-v2.6.3.zip.lnk, En cuarentena, 1000000, -67210770, 1.0.89579, D01B42590456D508FBFE71EE, dds, 03012664, ECEB9C421C1E7BE17E423DF8E4194F1D, 8F8C2C724D8DF53BF83C3DE1CD2B8F0215A7EA81E5A689B40FB829892CC08F59

Sector físico: 0
(No hay elementos maliciosos detectados)

WMI: 0
(No hay elementos maliciosos detectados)

(end)

**Comment by aloys-c** [comment]
Si es un error del malwarebytes
