### ISSUE TITLE
Downloading archive

### ISSUE THREAD

**Issue by wxman20** [Dakara93/wx2pfpx#20]
Hello,
Great program. Good job. I wanted to know if it was possible for a future update with the ability to download archive GRIB files, saying from 6 days ago??

**Comment by aloys-c** [comment]
Hello,

Probably not going to happen as almost nobody needs to make flights with past weather data... Best that can be done is to download the live data and then come back a few days later to use it. The option number_of_forecasts_to_keep can be used to retain previously downloaded data...
